import "../styles/main.scss";
import { SessionProvider } from "next-auth/react"
import Header from "../components/Header";

export const metadata = {
  title: 'ShellPage',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <SessionProvider>
          <Header />
          <main>
            <div className="container">
              {children}
            </div>
          </main>
        </SessionProvider>
      </body>
    </html>
  )
}
